<div style="background:#eef0f8;padding:15px 20px;border-left:6px solid #4a5cff;">
<p style="margin:0;color:#4a5cff;font-size:12px;font-weight:bold;letter-spacing:4px;">
</p>

<h1 style="margin:8px 0 0 0;color:#1a2340;">
Classification Algorithm
</h1>
</div>

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)
n = 10000

df = pd.DataFrame({
    "Age" : np.random.randint(17, 26, n),
    "Gender" : np.random.choice(["Male","Female"], n),
    "Attendence" : np.random.randint(40, 101, n),
    "CGPA" : np.round(np.random.uniform(4.5, 10, n),2),
    "Backlogs":np.random.randint(0,8,n),
    "FamilyIncome": np.random.randint(150000, 12000000, n),
    "StudyHours": np.round(np.random.uniform(0.5,8,n),1),
    "Scholarship": np.random.choice([0,1],n, p=[0.7,0.3]),
    "InternetAccess": np.random.choice([0,1],n, p=[0.15,0.85]),
    "Hostel": np.random.choice([0,1],n),
    "MentalStress": np.random.randint(1,11,n),
    "PartTimeJob": np.random.choice([0,1],n, p=[0.75,0.25])
})

In [3]:
df

,Age,Gender,Attendence,CGPA,Backlogs,FamilyIncome,StudyHours,Scholarship,InternetAccess,Hostel,MentalStress,PartTimeJob
0,23,Female,70,5.71,3,2744921,2.5,0,1,1,2,0
1,20,Female,45,6.17,6,8791810,1.2,0,1,0,1,1
2,24,Male,53,5.21,7,2874959,7.9,0,1,0,10,0
3,21,Female,97,5.87,0,10029209,6.2,0,0,1,5,0
4,23,Male,62,9.02,2,646632,0.5,0,1,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,Female,70,4.77,6,2549318,7.5,1,1,1,4,0
9996,23,Male,48,7.05,5,7781440,5.5,0,1,0,5,0
9997,22,Male,61,9.10,0,7274217,2.8,1,1,0,4,0
9998,25,Female,50,5.49,5,9772777,5.2,1,1,1,6,1
9999,23,Female,56,5.30,5,10765720,5.0,1,1,0,3,0

pd.set_option('display.expand_frame_repr', False)</br>
df

In [4]:
# Low attendance | Low CGPA | many Backlogs
risk = (
    (df["Attendence"] < 65).astype(int) +
    (df["CGPA"]<6.0).astype(int) +
    (df["Backlogs"]>= 3).astype(int) +
    (df["MentalStress"]>=8).astype(int) +
    (df["StudyHours"]< 2).astype(int)
)

df["Dropout"] = np.where(risk>=3, 1, 0)

In [5]:
df["Dropout"]

0       0
1       1
2       1
3       0
4       1
       ..
9995    0
9996    0
9997    0
9998    1
9999    1
Name: Dropout, Length: 10000, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop("Dropout", axis=1)
y = df["Dropout"]

In [8]:
# y
X = pd.get_dummies(X, drop_first=True)

In [9]:
X

,Age,Attendence,CGPA,Backlogs,FamilyIncome,StudyHours,Scholarship,InternetAccess,Hostel,MentalStress,PartTimeJob,Gender_Male
0,23,70,5.71,3,2744921,2.5,0,1,1,2,0,False
1,20,45,6.17,6,8791810,1.2,0,1,0,1,1,False
2,24,53,5.21,7,2874959,7.9,0,1,0,10,0,True
3,21,97,5.87,0,10029209,6.2,0,0,1,5,0,False
4,23,62,9.02,2,646632,0.5,0,1,0,8,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,70,4.77,6,2549318,7.5,1,1,1,4,0,False
9996,23,48,7.05,5,7781440,5.5,0,1,0,5,0,True
9997,22,61,9.10,0,7274217,2.8,1,1,0,4,0,True
9998,25,50,5.49,5,9772777,5.2,1,1,1,6,1,False
9999,23,56,5.30,5,10765720,5.0,1,1,0,3,0,False

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 41,
    stratify=y
)

In [11]:
X_train.shape

(8000, 12)

In [12]:
X_test.shape

(2000, 12)

In [13]:
y_train.shape

(8000,)

In [14]:
y_test.shape

(2000,)

In [17]:
!pip install scikit-learn xgboost

Requirement already satisfied: scikit-learn in c:\users\kambo\anaconda3\lib\site-packages (1.9.0)
Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\kambo\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in c:\users\kambo\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in c:\users\kambo\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\kambo\anaconda3\lib\site-packages (from scikit-learn) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\kambo\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
    --------------------------------------- 1.3/69.5 MB 7.1 MB/s eta 0:00:10
   - -------------------------------------- 2.6/69.5 MB 6.9 MB/s eta 0:00:10
   -- ------------------------------------- 3.9/69.5 MB 6.4 MB/s eta 0:00:11
   -- ------------------------------------- 5.0/69.5 MB 6.2 MB/s eta 0:00:11
   --- ------------------------------------ 5.5/69.5 MB 5.8 MB/s eta 0:00:12
   --- ------------------------------------ 6.3/69.5 MB 5.2 MB/s eta 0:00:13
   ---- ----------------------------------- 7.1/69.5 MB 4.9 MB/s eta 0:00:13
   ---- ----------------------------------- 7.9/69.5 MB 4.8 MB/s eta 0:00:13
   ---- ----------------------------------- 8.7/69.5 MB 4.7 MB/s eta 0:00:13
   ----- ---------------------------------- 9.7/69.5 MB 4.7 MB/s eta 0:00:13
   ----- ---------------------------------- 10.2/69.5 MB 4.6 MB/s eta 0:00:13
   ------ --------------------------------- 11.3/69.5 MB 4.6 MB/s eta 0:00:13
   ------ --------------------------------- 11.5/69.5 MB 4.4 MB/s eta 0:00:14
   ------ --------------------------------- 11.8/69.5 MB 4.3 MB/s eta 0:00:14
   ------ --------------------------------- 11.8/69.5 MB 4.3 MB/s eta 0:00:14
   ------ --------------------------------- 11.8/69.5 MB 4.3 MB/s eta 0:00:14
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------ --------------------------------- 12.1/69.5 MB 3.6 MB/s eta 0:00:17
   ------- -------------------------------- 12.3/69.5 MB 2.2 MB/s eta 0:00:26
   ------- -------------------------------- 12.3/69.5 MB 2.2 MB/s eta 0:00:26
   ------- -------------------------------- 12.6/69.5 MB 2.1 MB/s eta 0:00:27
   ------- -------------------------------- 12.8/69.5 MB 2.1 MB/s eta 0:00:28
   ------- -------------------------------- 13.1/69.5 MB 2.0 MB/s eta 0:00:28
   ------- -------------------------------- 13.1/69.5 MB 2.0 MB/s eta 0:00:28
   ------- -------------------------------- 13.1/69.5 MB 2.0 MB/s eta 0:00:28
   ------- -------------------------------- 13.4/69.5 MB 1.9 MB/s eta 0:00:30
   ------- -------------------------------- 13.6/69.5 MB 1.9 MB/s eta 0:00:30
   ------- -------------------------------- 13.9/69.5 MB 1.9 MB/s eta 0:00:30
   -------- ------------------------------- 14.4/69.5 MB 1.9 MB/s eta 0:00:30
   -------- ------------------------------- 14.7/69.5 MB 1.9 MB/s eta 0:00:30
   -------- ------------------------------- 14.9/69.5 MB 1.9 MB/s eta 0:00:30
   -------- ------------------------------- 15.2/69.5 MB 1.9 MB/s eta 0:00:30
   --------- ------------------------------ 15.7/69.5 MB 1.9 MB/s eta 0:00:29
   --------- ------------------------------ 16.3/69.5 MB 1.9 MB/s eta 0:00:29
   --------- ------------------------------ 16.5/69.5 MB 1.9 MB/s eta 0:00:29
   --------- ------------------------------ 17.0/69.5 MB 1.9 MB/s eta 0:00:28
   ---------- ----------------------------- 17.6/69.5 MB 1.9 MB/s eta 0:00:28
   ---------- ----------------------------- 18.1/69.5 MB 1.9 MB/s eta 0:00:27
   ---------- ----------------------------- 18.9/69.5 MB 2.0 MB/s eta 0:00:26
   ----------- ---------------------------- 19.7/69.5 MB 2.0 MB/s eta 0:00:26
   ----------- ---------------------------- 20.2/69.5 MB 2.0 MB/s eta 0:00:25
   ----------- ---------------------------- 20.7/69.5 MB 2.0 MB/s eta 0:00:25
   ------------ --------------------------- 21.5/69.5 MB 2.0 MB/s eta 0:00:24
   ------------ --------------------------- 22.0/69.5 MB 2.1 MB/s eta 0:00:24
   ------------ --------------------------- 22.3/69.5 MB 2.1 MB/s eta 0:00:24
   ------------ --------------------------- 22.5/69.5 MB 2.0 MB/s eta 0:00:24
   ------------- -------------------------- 22.8/69.5 MB 2.0 MB/s eta 0:00:24
   ------------- -------------------------- 23.3/69.5 MB 2.0 MB/s eta 0:00:23
   ------------- -------------------------- 23.9/69.5 MB 2.0 MB/s eta 0:00:23
   -------------- ------------------------- 24.6/69.5 MB 2.1 MB/s eta 0:00:22
   -------------- ------------------------- 25.2/69.5 MB 2.1 MB/s eta 0:00:22
   -------------- ------------------------- 25.2/69.5 MB 2.1 MB/s eta 0:00:22
   -------------- ------------------------- 25.7/69.5 MB 2.1 MB/s eta 0:00:22
   -------------- ------------------------- 26.0/69.5 MB 2.1 MB/s eta 0:00:22
   --------------- ------------------------ 26.2/69.5 MB 2.0 MB/s eta 0:00:22
   --------------- ------------------------ 26.5/69.5 MB 2.0 MB/s eta 0:00:22
   --------------- ------------------------ 27.0/69.5 MB 2.0 MB/s eta 0:00:22
   --------------- ------------------------ 27.3/69.5 MB 2.0 MB/s eta 0:00:21
   --------------- ------------------------ 27.5/69.5 MB 2.0 MB/s eta 0:00:21
   ---------------- ----------------------- 28.0/69.5 MB 2.0 MB/s eta 0:00:21
   ---------------- ----------------------- 28.6/69.5 MB 2.0 MB/s eta 0:00:21
   ---------------- ----------------------- 29.1/69.5 MB 2.0 MB/s eta 0:00:20
   ---------------- ----------------------- 29.4/69.5 MB 2.0 MB/s eta 0:00:20
   ---------------- ----------------------- 29.4/69.5 MB 2.0 MB/s eta 0:00:20
   ----------------- ---------------------- 29.6/69.5 MB 2.0 MB/s eta 0:00:21
   ----------------- ---------------------- 29.9/69.5 MB 2.0 MB/s eta 0:00:21
   ----------------- ---------------------- 30.1/69.5 MB 2.0 MB/s eta 0:00:21
   ----------------- ---------------------- 30.7/69.5 MB 2.0 MB/s eta 0:00:20
   ------------------ --------------------- 31.5/69.5 MB 2.0 MB/s eta 0:00:20
   ------------------ --------------------- 32.5/69.5 MB 2.0 MB/s eta 0:00:19
   ------------------- -------------------- 33.3/69.5 MB 2.1 MB/s eta 0:00:18
   ------------------- -------------------- 34.3/69.5 MB 2.1 MB/s eta 0:00:17
   ------------------- -------------------- 34.6/69.5 MB 2.1 MB/s eta 0:00:17
   -------------------- ------------------- 35.1/69.5 MB 2.1 MB/s eta 0:00:17
   -------------------- ------------------- 35.4/69.5 MB 2.1 MB/s eta 0:00:17
   -------------------- ------------------- 35.7/69.5 MB 2.1 MB/s eta 0:00:17
   -------------------- ------------------- 36.2/69.5 MB 2.1 MB/s eta 0:00:17
   -------------------- ------------------- 36.4/69.5 MB 2.1 MB/s eta 0:00:16
   --------------------- ------------------ 36.7/69.5 MB 2.1 MB/s eta 0:00:16
   --------------------- ------------------ 37.0/69.5 MB 2.1 MB/s eta 0:00:16
   --------------------- ------------------ 37.5/69.5 MB 2.1 MB/s eta 0:00:16
   --------------------- ------------------ 37.7/69.5 MB 2.1 MB/s eta 0:00:16
   --------------------- ------------------ 38.0/69.5 MB 2.1 MB/s eta 0:00:16
   ---------------------- ----------------- 38.3/69.5 MB 2.0 MB/s eta 0:00:16
   ---------------------- ----------------- 39.1/69.5 MB 2.0 MB/s eta 0:00:15
   ---------------------- ----------------- 39.8/69.5 MB 2.1 MB/s eta 0:00:15
   ----------------------- ---------------- 40.4/69.5 MB 2.1 MB/s eta 0:00:15
   ----------------------- ---------------- 40.6/69.5 MB 2.1 MB/s eta 0:00:14
   ----------------------- ---------------- 40.9/69.5 MB 2.1 MB/s eta 0:00:14
   ----------------------- ---------------- 41.2/69.5 MB 2.1 MB/s eta 0:00:14
   ----------------------- ---------------- 41.4/69.5 MB 2.1 MB/s eta 0:00:14
   ----------------------- ---------------- 41.4/69.5 MB 2.1 MB/s eta 0:00:14
   ----------------------- ---------------- 41.7/69.5 MB 2.0 MB/s eta 0:00:14
   ------------------------ --------------- 41.9/69.5 MB 2.0 MB/s eta 0:00:14
   ------------------------ --------------- 42.2/69.5 MB 2.0 MB/s eta 0:00:14
   ------------------------ --------------- 42.7/69.5 MB 2.0 MB/s eta 0:00:14
   ------------------------- -------------- 43.5/69.5 MB 2.0 MB/s eta 0:00:13
   ------------------------- -------------- 44.0/69.5 MB 2.0 MB/s eta 0:00:13
   ------------------------- -------------- 44.6/69.5 MB 2.0 MB/s eta 0:00:13
   -------------------------- ------------- 45.6/69.5 MB 2.1 MB/s eta 0:00:12
   -------------------------- ------------- 46.7/69.5 MB 2.1 MB/s eta 0:00:11
   --------------------------- ------------ 47.4/69.5 MB 2.1 MB/s eta 0:00:11
   --------------------------- ------------ 48.0/69.5 MB 2.1 MB/s eta 0:00:11
   ---------------------------- ----------- 49.3/69.5 MB 2.1 MB/s eta 0:00:10
   ---------------------------- ----------- 50.1/69.5 MB 2.2 MB/s eta 0:00:10
   ----------------------------- ---------- 50.9/69.5 MB 2.2 MB/s eta 0:00:09
   ----------------------------- ---------- 51.9/69.5 MB 2.2 MB/s eta 0:00:09
   ------------------------------ --------- 52.7/69.5 MB 2.2 MB/s eta 0:00:08
   ------------------------------ --------- 53.0/69.5 MB 2.2 MB/s eta 0:00:08
   ------------------------------ --------- 53.7/69.5 MB 2.2 MB/s eta 0:00:08
   ------------------------------- -------- 54.0/69.5 MB 2.2 MB/s eta 0:00:07
   ------------------------------- -------- 54.5/69.5 MB 2.2 MB/s eta 0:00:07
   ------------------------------- -------- 55.3/69.5 MB 2.2 MB/s eta 0:00:07
   -------------------------------- ------- 56.1/69.5 MB 2.2 MB/s eta 0:00:06
   -------------------------------- ------- 56.9/69.5 MB 2.3 MB/s eta 0:00:06
   --------------------------------- ------ 57.7/69.5 MB 2.3 MB/s eta 0:00:06
   --------------------------------- ------ 58.5/69.5 MB 2.3 MB/s eta 0:00:05
   ---------------------------------- ----- 59.2/69.5 MB 2.3 MB/s eta 0:00:05
   ---------------------------------- ----- 60.0/69.5 MB 2.3 MB/s eta 0:00:05
   ----------------------------------- ---- 61.1/69.5 MB 2.3 MB/s eta 0:00:04
   ----------------------------------- ---- 62.1/69.5 MB 2.3 MB/s eta 0:00:04
   ------------------------------------ --- 62.9/69.5 MB 2.4 MB/s eta 0:00:03
   ------------------------------------ --- 64.0/69.5 MB 2.4 MB/s eta 0:00:03
   ------------------------------------- -- 64.5/69.5 MB 2.4 MB/s eta 0:00:03
   ------------------------------------- -- 64.7/69.5 MB 2.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.3/69.5 MB 2.4 MB/s eta 0:00:02
   ------------------------------------- -- 65.5/69.5 MB 2.4 MB/s eta 0:00:02
   -------------------------------------- - 66.1/69.5 MB 2.4 MB/s eta 0:00:02
   -------------------------------------- - 66.8/69.5 MB 2.4 MB/s eta 0:00:02
   -------------------------------------- - 67.4/69.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  68.2/69.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  69.2/69.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 2.4 MB/s  0:00:28
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\kambo\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\kambo\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\kambo\anaconda3\Lib\site-packages)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

In [ ]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN":KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "XGBoost": XGBClassifier(),
    "Naive Bayes": GaussianNB()  
}

In [21]:
result = []
for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

In [22]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results = []

for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict class labels
    y_pred = model.predict(X_test)

    # Predict probabilities
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        # SVM without probability=True
        y_prob = y_pred

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "ROC AUC": roc_auc_score(y_test, y_prob)
    })

C:\Users\kambo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\kambo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [23]:
result_df = pd.DataFrame(results)
result_df = result_df.sort_values(
    by="Accuracy",
    ascending = False
)
result_df

                 Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
3        Random Forest    1.0000   1.000000  1.000000  1.000000  1.000000
5              XGBoost    1.0000   1.000000  1.000000  1.000000  1.000000
2        Decision Tree    0.9990   0.997908  0.997908  0.997908  0.998625
0  Logistic Regression    0.8605   0.769648  0.594142  0.670602  0.906342
4                  SVM    0.7610   0.000000  0.000000  0.000000  0.500000
6          Naive Bayes    0.7610   0.000000  0.000000  0.000000  0.647090
1                  KNN    0.7015   0.203980  0.085774  0.120766  0.486826